var legionjewelsinfo = {
	"111":{"name":"Flawless Execution","sd":{"1":"80% Crit.Chance"}},
	"112":{"name":"Brutal Execution","sd":{"1":"+40% Crit.Multi"}},
	"113":{"name":"Eternal Resilience","sd":{"1":"1 EC per sec when Hit"}},
	"114":{"name":"Eternal Fortitude","sd":{"1":"8% Armour per EC"}},
	"115":{"name":"Eternal Dominance","sd":{"1":"10% Damage per EC"}},
	"116":{"name":"Eternal Fervour","sd":{"1":"10% Chance FC on hit"}},
	"117":{"name":"Eternal Adaptiveness","sd":{"1":"8% Evasion per FC"}},
	"118":{"name":"Eternal Bloodlust","sd":{"1":"10% Damage per FC"}},
	"119":{"name":"Eternal Subjugation","sd":{"1":"15% PC on crit"}},
	"120":{"name":"Eternal Separation","sd":{"1":"4% ES per PC"}},
	"121":{"name":"Eternal Exploitation","sd":{"1":"10% Damage per PC"}},
	"122":{"name":"Rites of Lunaris","sd":{"1":"30% Chill Effect"}},
	"123":{"name":"Rites of Solaris","sd":{"1":"80% Avoid being Chilled"}},
	"124":{"name":"Virtue Gem Surgery","sd":{"1":"30% Shock Effect"}},
	"125":{"name":"Rural Life","sd":{"1":"80% Avoid being Shocked"}},
	"126":{"name":"City Walls","sd":{"1":"+8% Block Attack Damage"}},
	"127":{"name":"Sceptre Pinnacle","sd":{"1":"8% Block Spell Damage"}},
	"128":{"name":"Secret Tunnels","sd":{"1":"20% Avoid Elemental Ailments"}},
	"129":{"name":"Purity Rebel","sd":{"1":"+12% Suppress Spell Damage"}},
	"130":{"name":"Superiority","sd":{"1":"12% Aura Effect"}},
	"131":{"name":"Slum Lord","sd":{"1":"80% Minions DAMAGE"}},
	"132":{"name":"Axiom Warden","sd":{"1":"80% Minions LIFE"}},
	"133":{"name":"Gemling Inquisition","sd":{"1":"80% Spell Damage"}},
	"134":{"name":"Gemling Ambush","sd":{"1":"80% Crit.Chance SPELLS"}},
	"135":{"name":"Night of a Thousand Ribbons","sd":{"1":"80% Fire Attack Damage"}},
	"136":{"name":"Bloody Flowers' Rebellion","sd":{"1":"80% Cold Attackdmg"}},
	"137":{"name":"Chitus' Heart","sd":{"1":"80% Lightning Attackdmg"}},
	"138":{"name":"Gemling Training","sd":{"1":"80% Physical Damage"}},
	"139":{"name":"Rigwald's Might","sd":{"1":"80% Melee Physical Damage"}},
	"140":{"name":"Geofri's End","sd":{"1":"50% Bleed Damage"}},
	"141":{"name":"Lioneye's Focus","sd":{"1":"80% Projectile Attack Damage"}},
	"142":{"name":"Voll's Coup","sd":{"1":"15% Attack Speed"}},
	"143":{"name":"Dialla's Wit","sd":{"1":"15% Cast Speed"}},
	"144":{"name":"Discerning Taste","sd":{"1":"40% Rarity"}},
	"145":{"name":"Gleaming Legion","sd":{"1":"80% Armour"}},
	"146":{"name":"Shadowy Streets","sd":{"1":"80% Evasion Rating"}},
	"147":{"name":"Crematorium Worker","sd":{"1":"+50% Fire Resistance"}},
	"148":{"name":"Street Urchin","sd":{"1":"+50% Cold Resistance"}},
	"149":{"name":"Baleful Augmentation","sd":{"1":"+50% Lightning Resistance"}},
	"150":{"name":"With Eyes Open","sd":{"1":"+37% Chaos Resistance"}},
	"151":{"name":"Robust Diet","sd":{"1":"10% Maximum Life"}},
	"152":{"name":"Pooled Resources","sd":{"1":"30% Maximum Mana"}},
	"153":{"name":"Laureate","sd":{"1":"50% Mana Regen"}},
	"154":{"name":"War Games","sd":{"1":"25% Accuracy"}},
	"155":{"name":"Freshly Brewed","sd":{"1":"20% Flask Duration"}}};